version: '3.8'

services:
  web:
    build: .
    container_name: django_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=True

  stripe:
    image: stripe/stripe-cli:latest
    container_name: stripe_cli
    command: listen --forward-to http://web:8000/payment/webhook/
    environment:
      - STRIPE_API_KEY=${STRIPE_SECRET_KEY}
    depends_on:
      - web
    volumes:
      - .:/app